insert into emailTypes (id,emailType) values (1,'Parent Registration');
insert into emailTypes (id,emailType) values (2,'Individual Registration');
insert into emailTypes (id,emailType) values (3,'Organiser Registration');
insert into emailTypes (id,emailType) values (4,'Reset Password');
insert into emailTypes (id,emailType) values (5,'Confirm Payment Details');
insert into emailTypes (id,emailType) values (6,'Charity');
insert into emailTypes (id,emailType) values (7,'Delay');
insert into emailTypes (id,emailType) values (8,'Deadline');
insert into emailTypes (id,emailType) values (9,'Parent Purchase');
insert into emailTypes (id,emailType) values (10,'Individual Purchase');
insert into emailTypes (id,emailType) values (11,'Parent Registration Bluwave');
insert into emailTypes (id,emailType) values (12,'Individual Registration Bluwave');
insert into emailTypes (id,emailType) values (13,'Organiser Registration Bluwave');
insert into emailTypes (id,emailType) values (14,'Confirmed Charity Amount Bluwave');
insert into emailTypes (id,emailType) values (15,'Parent 3 days to Deadline Reminder');
insert into emailTypes (id,emailType) values (16,'Parent 1 day to Deadline Reminder');
insert into emailTypes (id,emailType) values (17,'Individual Purchase Bluwave');
insert into emailTypes (id,emailType) values (18,'Parent Purchase Bluwave');
insert into emailTypes (id,emailType) values (19,'Noticed No Purchase After Sign Up');